title: Screem Soft
description: My site for all of my hobbies.
theme: just-the-docs
color_scheme: dark

url: https://docs.screem.io

aux_links:
  "Join the support server":
  -  "//discord.gg/cRSnvRZD"

aux_links_new_tab: true

heading_anchors: true

footer_content: "Copyright &copy; 2025 Screem Soft"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
